import Header from "@/include/Header";
import "@/app/css/index.css";
import Side from "@/include/Side";
import Main from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <div className="main">
          <Side />
          <section>
            {/* <Main /> */}
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
