import { Inter } from "next/font/google";
import "@/css/layout.css";
import Link from "next/link";
import Header from "./include/Header";
import Nav from "./include/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Header />
        <div className="main">
          <Nav />
          <section>{children}</section>
        </div>
      </body>
    </html>
  );
}
